os:
  - linux

language: php

php:
  - '7.4'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 12
  - npm install npm@latest -g
  - npm install -g eslintnpm
  - npm install

script:
  - phpcs app
  - eslint resources/js --max-warnings=-1 --ext .js,.vue
  - vendor/bin/phpunit --coverage-text
  - npm run production
